### ISSUE TITLE
Too soon for an issue

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [natario1/whatsapp-database-merger#1]
Hey, thanks for the work. I have very limited experience with Java, tried building the project but got some error. I know very little to conclude what went wrong. Here's the screenshot.

![image](https://user-images.githubusercontent.com/52948878/156899877-1b5a7beb-5dc8-47a8-afc0-f7e5ea65a797.png)

Would it be possible for you to release a jar for this?

**Comment by YuvrajRaghuvanshiS** [comment]
Turned out my JAVA_HOME had jre, it required jdk. Still no idea what was the issue lol. Build successful.

**Comment by YuvrajRaghuvanshiS** [comment]
![image](https://user-images.githubusercontent.com/52948878/156900537-a6eb1b8c-3f90-44a2-9126-f0f9d7ee2f0d.png)

How do I proceed?

**Comment by natario1** [comment]
I think you're just missing the required argument. Try ./gradlew run --args="<path to folder as described in README>"

**Comment by YuvrajRaghuvanshiS** [comment]
There was some exception while merging most likely because of schema difference between two databases or between database and this program. What version of WA you were using when you pulled database from phone? I will try to get my databases from that versions of WA.

**Comment by YuvrajRaghuvanshiS** [comment]
For me it is not excluding problematic columns, That expression tree.

**Comment by natario1** [comment]
Latest version. What's the error?

**Comment by YuvrajRaghuvanshiS** [comment]
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (Expression tree is too large (maximum depth 1000))

**Comment by natario1** [comment]
In which table and column? It is possible to ignore columns with a little change in the source code.

**Comment by YuvrajRaghuvanshiS** [comment]
```
[*] processing table messages_quotes
	- input\old_1_msgstore.db columns: [_id, key_remote_jid, key_from_me, key_id, status, needs_push, data, timestamp, media_url, media_mime_type, media_wa_type, media_size, media_name, media_caption, media_hash, media_duration, origin, latitude, longitude, thumb_image, remote_resource, received_timestamp, send_timestamp, receipt_server_timestamp, receipt_device_timestamp, read_device_timestamp, played_device_timestamp, raw_data, recipient_count, participant_hash, starred, quoted_row_id, mentioned_jids, multicast_id, edit_version, media_enc_hash, payment_transaction_id, forwarded, preview_type, send_count, lookup_tables, future_message_type, message_add_on_flags]
	- output\msgstore.db columns: [_id, key_remote_jid, key_from_me, key_id, status, needs_push, data, timestamp, media_url, media_mime_type, media_wa_type, media_size, media_name, media_caption, media_hash, media_duration, origin, latitude, longitude, thumb_image, remote_resource, received_timestamp, send_timestamp, receipt_server_timestamp, receipt_device_timestamp, read_device_timestamp, played_device_timestamp, raw_data, recipient_count, participant_hash, starred, quoted_row_id, mentioned_jids, multicast_id, edit_version, media_enc_hash, payment_transaction_id, forwarded, preview_type, send_count, lookup_tables, future_message_type, message_add_on_flags]
[*] messages_quotes: source elements 11478, destination elements 40778
[*] messages_quotes: applying offset 44133 to primary key.
[*] messages_quotes: editing column quoted_row_id, because it references table messages_quotes which was previously edited.
[*] messages_quotes: about to append 11478 rows
	appended 500/11478...
	appended 1000/11478...
	appended 1500/11478...
	appended 2000/11478...
	appended 2500/11478...
	appended 3000/11478...
	appended 3500/11478...
	appended 4000/11478...
	appended 4500/11478...
	appended 5000/11478...
	appended 5500/11478...
	appended 6000/11478...
	appended 6500/11478...
	appended 7000/11478...

> Task :run FAILED
2 actionable tasks: 2 executed

```
 
That is point where it fails...

**Comment by YuvrajRaghuvanshiS** [comment]
I have managed to create build scan for that but I am not sure how safe is that to share.

**Comment by YuvrajRaghuvanshiS** [comment]
Can I delete these failed cells from db and re-run?

**Comment by natario1** [comment]
You need to edit these lines: https://github.com/natario1/whatsapp-database-merger/blob/main/src/main/kotlin/dev/natario/Table.kt#L13-L15 to be like this:

    messages_quotes(
        refs = listOf(Ref("quoted_row_id", "messages_quotes")),
        dropFailingBatches = false,
        maxBatch = 1
    ),
    
If it still fails, try `dropFailingBatches = true` which will do what you asked.

**Comment by YuvrajRaghuvanshiS** [comment]
Thank you for that, it seems to be working. Also, is there any way that I can set those blobs to null where this fails and later fill those manually?

**Comment by YuvrajRaghuvanshiS** [comment]
As of now it just exits with 
```
	appended 7162/11478...
	appended 7163/11478...
	appended 7164/11478...

> Task :run FAILED
2 actionable tasks: 2 executed
```

**Comment by natario1** [comment]
Yeah now change that value to true. Also use --stacktrace to get more error info.

**Comment by YuvrajRaghuvanshiS** [comment]
It failed on "chat" table, but that is on me, incompatible versions. I just created those new cols. I'll update once it is done.

**Comment by YuvrajRaghuvanshiS** [comment]
I created those missing attributes and re-run the process. It all worked perfectly, thank you for patiently guiding me through. 

Also I learned a lot while figuring this project out, like adding those parameters which helped debug on the fly. Amazing work :D

**Comment by natario1** [comment]
Great!
