### ISSUE TITLE
Convert old database to new schema

### ISSUE THREAD

**Issue by Azfarrr** [natario1/whatsapp-database-merger#8]
Sorry if this is a bit out of topic. 

Currently I want to merge two databases, an old one where messages are stored in `messages` table, and a new db where messages are stored in `message` table.

I read the new changes made by [MrBarbie](https://github.com/MrBarbie) that makes  merging between databases with the new, mid-2022 schema possible. But mine is on different schemas.

I tried restoring the old db into the latest whatsapp version, and creating a backup, then restoring again using the newly generated backup file. But the new backup file is still using old schema, and I'm at a loss here.

So back to the question, is there a way to convert the old db schema into the new one? I know that it is possible to generate a SQL query to do that but the whatsapp db structure is a bit overwhelming for me.

**Comment by Azfarrr** [comment]
I tried restoring again using the old db, then after a week of using whatsapp as usual, I tried creating backup again. The database exported is already converted to the new schema.

I think Whatsapp needs some time to do db migrate task in the background. Closing this issue.

**Comment by Rainy-Window** [comment]
have you found any solution to this aside from using WA for a week? 
i've about 3 old backups and they sure have different schema.
1.db >> from 2018 to 2021 Aug
2.db >> 2021 Oct
3.db >> 2021 to 2022 Aug
4.db >> 2022 to current 2023..

is there any way to make them of the same schema please?
